### ISSUE TITLE
NameError: name 'K' is not defined

### ISSUE THREAD

**Issue by kunkun1230** [farizrahman4u/recurrentshop#119]
when i import recurrentshop， i got this back

`  File "D:\Program\Anaconda\lib\site-packages\recurrentshop-1.0.0-py3.7.egg\recurrentshop\engine.py", line 10, in <module>
    if K.backend() == 'tensorflow':

NameError: name 'K' is not defined`

what should i do ?
My backend is theano for keras

**Comment by absognety** [comment]
https://github.com/farizrahman4u/recurrentshop/pull/120#issue-378817838
