### ISSUE TITLE
NameError: name 'activations' is not defined

### ISSUE THREAD

**Issue by ShivamPanchal** [farizrahman4u/recurrentshop#121]
I am using the latest installation as per this - https://github.com/farizrahman4u/seq2seq/issues/276#issuecomment-583960729

Now, I am trying to call you Seq2Seq model from recurrentshop, but it gives me an import error.

`51 model.add(Embedding(NUM_WORDS, 200, input_length=MAX_LEN))
---> 52 attn = AttentionSeq2Seq(batch_input_shape=(None, MAX_LEN, 200), hidden_dim=10, output_length=MAX_LEN, output_dim=NUM_WORDS, depth=1)`

`NameError: name 'activations' is not defined`

Its note from keras, I tried installing other versions also.

**Comment by ShivamPanchal** [comment]
Aye! I used this piece of code and it started working.


'!pip install keras==2.2.4
!git clone https://www.github.com/farizrahman4u/recurrentshop.git
%cd recurrentshop
!python setup.py install
!sud pip install git+https://github.com/farizrahman4u/seq2seq.git'

Thanks, I am closing the issue

**Comment by kp-444** [comment]
ran this code snippet on my Jupyter notebook(was desperate to solve the issue), got unexpected errors, pd.read_csv could not access the local file uploaded and there were errors with numpy module as well.

Original code :
layers = [[20],[40,20],[45,30,15]]
activation = ['sigmoid','relu']
param_grid = dict(layers = layers,activation=activations,batch_size=[128,256],epochs=[30])
grid = GridSearchCV(estimator=model, param_grid=param_grid,cv=5)

Error :
NameError                                 Traceback (most recent call last)
<ipython-input-16-7db15ffa0834> in <module>
      1 layers = [[20],[40,20],[45,30,15]]
      2 activation = ['sigmoid','relu']
----> 3 param_grid = dict(layers = layers,activation=activations,batch_size=[128,256],epochs=[30])
      4 grid = GridSearchCV(estimator=model, param_grid=param_grid,cv=5)

NameError: name 'activations' is not defined
